### ISSUE TITLE
Feature: Article

### ISSUE THREAD

**Issue by TrangDoThuy** [TrangDoThuy/CliMate-App#2]
# Epic Title

Feature: Article

## Epic Description

This feature will display the article related to Climate change and the environment. Users can read and leave comments.

![articlePage](https://user-images.githubusercontent.com/30380242/103734706-86c5f900-5027-11eb-9f22-c2248fa7fefb.jpg)

## List of Tasks
- [ ] Task1: Initial Layout #3 
- [ ] Task 2: Display article when the user clicks #4 
- [ ] Task 3: Display comments #5
